# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='global_sync',
    source=[
        'global_sync.cpp',
    ],
    LIBDEPS=[
        'global_fetcher',
        '$BUILD_DIR/mongo/db/repl/oplog',
        '$BUILD_DIR/mongo/db/repl/abstract_async_component',
        '$BUILD_DIR/mongo/db/repl/data_replicator_external_state_impl',
        '$BUILD_DIR/mongo/db/repl/oplog_interface_local',
        '$BUILD_DIR/mongo/db/repl/oplog_interface_remote',
        '$BUILD_DIR/mongo/db/repl/repl_coordinator_interface',
        '$BUILD_DIR/mongo/db/repl/rollback_impl',
        '$BUILD_DIR/mongo/db/repl/rollback_source_impl',
        '$BUILD_DIR/mongo/db/repl/rs_rollback',
        '$BUILD_DIR/mongo/db/repl/storage_interface',
        '$BUILD_DIR/mongo/db/repl/sync_source_resolver',
        '$BUILD_DIR/mongo/client/connection_pool',
        '$BUILD_DIR/mongo/client/fetcher',
        '$BUILD_DIR/mongo/db/concurrency/write_conflict_exception',
        '$BUILD_DIR/mongo/db/server_parameters',
        '$BUILD_DIR/mongo/db/service_context',
        '$BUILD_DIR/mongo/util/concurrency/thread_pool',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/executor/thread_pool_task_executor',
        '$BUILD_DIR/mongo/db/commands/test_commands_enabled',
    ],
)

env.Library(
    target='global_fetcher',
    source=[
        'global_fetcher.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/repl/abstract_oplog_fetcher',
        '$BUILD_DIR/mongo/db/repl/repl_coordinator_interface',
        '$BUILD_DIR/mongo/db/repl/replica_set_messages',
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/namespace_string',
        '$BUILD_DIR/mongo/db/stats/counters',
        '$BUILD_DIR/mongo/db/stats/timer_stats',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/commands/server_status_core',
    ],
)
